// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKetb3tk2SO-kDOYQ4UiIEd67dK4VRbRE',
    appId: '1:622232964157:web:42aac86fc8bb80eddcee54',
    messagingSenderId: '622232964157',
    projectId: 'pemmobile-c404e',
    authDomain: 'pemmobile-c404e.firebaseapp.com',
    storageBucket: 'pemmobile-c404e.appspot.com',
    measurementId: 'G-CV2B1Z46RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQO5WXUbCRwLmtezUVMvzVdpq3Hl4QpyQ',
    appId: '1:622232964157:android:90bdc8799a3a149adcee54',
    messagingSenderId: '622232964157',
    projectId: 'pemmobile-c404e',
    storageBucket: 'pemmobile-c404e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTIKpd1DHhcHs5pbBQ-wutZ5K0EhUr_0',
    appId: '1:622232964157:ios:25a992aa33905d92dcee54',
    messagingSenderId: '622232964157',
    projectId: 'pemmobile-c404e',
    storageBucket: 'pemmobile-c404e.appspot.com',
    iosBundleId: 'com.example.revisiAplikasiPertukaranMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuTIKpd1DHhcHs5pbBQ-wutZ5K0EhUr_0',
    appId: '1:622232964157:ios:25a992aa33905d92dcee54',
    messagingSenderId: '622232964157',
    projectId: 'pemmobile-c404e',
    storageBucket: 'pemmobile-c404e.appspot.com',
    iosBundleId: 'com.example.revisiAplikasiPertukaranMahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKetb3tk2SO-kDOYQ4UiIEd67dK4VRbRE',
    appId: '1:622232964157:web:ba697b0758b29228dcee54',
    messagingSenderId: '622232964157',
    projectId: 'pemmobile-c404e',
    authDomain: 'pemmobile-c404e.firebaseapp.com',
    storageBucket: 'pemmobile-c404e.appspot.com',
    measurementId: 'G-YP340NHY7Q',
  );
}
